import { useState } from 'react';
import { CheckCircle, Download, Loader2, Map, RotateCcw, Sparkles, Target } from 'lucide-react';
import { generateRoadmap, isHuggingFaceConfigured } from '../lib/huggingface';
import { incrementActivityMetric } from '../lib/activity';

type RoadmapPhase = {
  phase: number;
  title: string;
  goal: string;
  items: string[];
  project: string;
};

type GeneratedRoadmap = {
  title: string;
  estimatedTime: string;
  summary: string;
  phases: RoadmapPhase[];
};

const ROADMAP_OPTIONS = [
  { id: 'frontend', title: 'Frontend Developer' },
  { id: 'backend', title: 'Backend Developer' },
  { id: 'fullstack', title: 'Full Stack Developer' },
  { id: 'mobile', title: 'Mobile Developer' },
];

export default function Roadmap() {
  const [selectedPath, setSelectedPath] = useState('frontend');
  const [level, setLevel] = useState('beginner');
  const [roadmap, setRoadmap] = useState<GeneratedRoadmap | null>(null);
  const [rawRoadmap, setRawRoadmap] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const selectedTitle = ROADMAP_OPTIONS.find((option) => option.id === selectedPath)?.title || 'Developer';

  const handleGenerate = async () => {
    setLoading(true);
    setError('');
    setRawRoadmap('');
    setRoadmap(null);

    try {
      const generated = await generateRoadmap(selectedTitle, level);
      setRawRoadmap(generated);
      const parsed = parseRoadmap(generated, selectedTitle, level);
      incrementActivityMetric('roadmaps');
      setRoadmap(parsed);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not generate roadmap.');
    } finally {
      setLoading(false);
    }
  };

  const exportRoadmap = () => {
    if (!roadmap) return;
    const content = [
      roadmap.title,
      roadmap.estimatedTime,
      '',
      roadmap.summary,
      '',
      ...roadmap.phases.flatMap((phase) => [
        `Phase ${phase.phase}: ${phase.title}`,
        `Goal: ${phase.goal}`,
        ...phase.items.map((item, index) => `${index + 1}. ${item}`),
        `Project: ${phase.project}`,
        '',
      ]),
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${selectedPath}-${level}-roadmap.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-white px-4 py-8 sm:py-10">
      <div className="mx-auto max-w-6xl">
        <div className="mb-10 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-zinc-50 px-4 py-2 shadow-sm">
            <Sparkles size={16} className="text-zinc-700" />
            <span className="text-sm font-semibold text-zinc-700">
              {isHuggingFaceConfigured ? 'AI roadmap generator' : 'Demo roadmap generator'}
            </span>
          </div>
          <h1 className="mb-4 text-3xl font-semibold tracking-tight text-zinc-950 sm:text-5xl">Generate Your Roadmap</h1>
          <p className="mx-auto max-w-2xl text-sm leading-6 text-zinc-600 sm:text-lg">
            Choose a path and skill level, then get a clean phase-by-phase roadmap generated by AI.
          </p>
        </div>

        <div className="mb-8 rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-8">
          <div className="mb-8">
            <h2 className="mb-4 text-xl font-semibold tracking-tight text-zinc-950">Choose your learning path</h2>
            <div className="grid gap-4 md:grid-cols-2">
              {ROADMAP_OPTIONS.map((option) => (
                <button
                  key={option.id}
                  onClick={() => setSelectedPath(option.id)}
                  disabled={loading}
                  className={`rounded-3xl border p-5 text-left transition-all disabled:cursor-not-allowed disabled:opacity-60 ${
                    selectedPath === option.id
                      ? 'border-zinc-950 bg-zinc-950 text-white shadow-sm'
                      : 'border-zinc-200 bg-white hover:bg-zinc-50'
                  }`}
                >
                  <div className={`mb-4 flex h-14 w-14 items-center justify-center rounded-xl ${selectedPath === option.id ? 'bg-white text-black' : 'bg-zinc-100 text-zinc-700'}`}>
                    <Map size={26} />
                  </div>
                  <h3 className={selectedPath === option.id ? 'text-lg font-semibold text-white' : 'text-lg font-semibold text-zinc-950'}>{option.title}</h3>
                  <p className={selectedPath === option.id ? 'mt-2 text-sm leading-6 text-zinc-300' : 'mt-2 text-sm leading-6 text-zinc-600'}>A practical path from fundamentals to portfolio-ready projects.</p>
                </button>
              ))}
            </div>
          </div>

          <div className="mb-8">
            <h2 className="mb-4 text-xl font-semibold tracking-tight text-zinc-950">Current level</h2>
            <div className="grid gap-3 sm:grid-cols-3">
              {['beginner', 'intermediate', 'advanced'].map((item) => (
                <button
                  key={item}
                  onClick={() => setLevel(item)}
                  disabled={loading}
                  className={`rounded-2xl px-4 py-3 text-sm font-semibold capitalize transition-all disabled:cursor-not-allowed disabled:opacity-60 ${
                    level === item ? 'bg-black text-white shadow-sm' : 'border border-zinc-200 bg-white text-zinc-700 hover:bg-zinc-50'
                  }`}
                >
                  {item}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={() => void handleGenerate()}
            disabled={loading}
            className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-black px-8 py-4 font-semibold text-white shadow-sm transition-all hover:-translate-y-0.5 hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-60 sm:w-auto"
          >
            {loading ? <Loader2 size={20} className="animate-spin" /> : <Sparkles size={20} />}
            {loading ? 'Generating Roadmap...' : roadmap ? 'Regenerate Roadmap' : 'Generate My Roadmap'}
          </button>
        </div>

        {error && (
          <div className="mb-8 rounded-3xl border border-red-200 bg-red-50 p-5 text-sm leading-6 text-red-700">
            {error}
          </div>
        )}

        {loading && (
          <div className="rounded-2xl border border-zinc-200 bg-white p-10 text-center shadow-sm">
            <Loader2 size={34} className="mx-auto mb-4 animate-spin text-zinc-700" />
            <h2 className="text-xl font-semibold tracking-tight text-zinc-950">Building your roadmap</h2>
            <p className="mt-2 text-sm text-zinc-600">Asking AI for structured phases, projects, and milestones.</p>
          </div>
        )}

        {!loading && roadmap && (
          <div className="space-y-6">
            <div className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-6">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-start gap-4">
                  <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-zinc-100 text-zinc-700">
                    <Target size={28} />
                  </div>
                  <div>
                    <h2 className="text-2xl font-semibold tracking-tight text-zinc-950">{roadmap.title}</h2>
                    <p className="mt-1 text-sm font-semibold text-zinc-700">{roadmap.estimatedTime}</p>
                    <p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-600">{roadmap.summary}</p>
                  </div>
                </div>
                <div className="flex flex-col gap-2 sm:flex-row">
                  <button
                    onClick={exportRoadmap}
                    className="inline-flex items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 py-2 text-sm font-semibold text-zinc-700 transition hover:bg-zinc-50"
                  >
                    <Download size={18} />
                    Export
                  </button>
                  <button
                    onClick={() => {
                      setRoadmap(null);
                      setRawRoadmap('');
                      setError('');
                    }}
                    className="inline-flex items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 py-2 text-sm font-semibold text-zinc-700 transition hover:bg-zinc-50"
                  >
                    <RotateCcw size={18} />
                    New
                  </button>
                </div>
              </div>
            </div>

            <div className="space-y-5">
              {roadmap.phases.map((phase, index) => (
                <PhaseCard key={`${phase.phase}-${phase.title}`} phase={phase} index={index} />
              ))}
            </div>
          </div>
        )}

        {!loading && !roadmap && !error && (
          <div className="rounded-2xl border border-dashed border-zinc-200 bg-zinc-50 p-10 text-center text-sm text-zinc-500">
            Select your path and generate a roadmap to see AI-created phases here.
          </div>
        )}

        {rawRoadmap && !roadmap && (
          <details className="mt-6 rounded-3xl border border-white/70 bg-white/70 p-5 text-sm text-slate-600">
            <summary className="cursor-pointer font-semibold text-slate-900">Raw AI response</summary>
            <pre className="mt-4 overflow-x-auto whitespace-pre-wrap">{rawRoadmap}</pre>
          </details>
        )}
      </div>
    </div>
  );
}

function PhaseCard({ phase, index }: { phase: RoadmapPhase; index: number }) {
  return (
    <article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-6">
      <div className="mb-5 flex items-start gap-4">
        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-black font-bold text-white shadow-sm">
          {phase.phase || index + 1}
        </div>
        <div className="min-w-0 flex-1">
          <p className="mb-1 text-xs font-semibold uppercase tracking-[0.18em] text-zinc-500">Phase {phase.phase || index + 1}</p>
          <h3 className="text-xl font-semibold tracking-tight text-zinc-950">{phase.title}</h3>
          <p className="mt-2 text-sm leading-6 text-zinc-600">{phase.goal}</p>
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 sm:pl-16">
        {phase.items.map((item, itemIndex) => (
          <div key={`${item}-${itemIndex}`} className="flex items-start gap-3 rounded-xl border border-zinc-200 bg-zinc-50 p-4">
            <CheckCircle size={19} className="mt-0.5 shrink-0 text-zinc-700" />
            <span className="text-sm font-medium leading-6 text-zinc-700">{item}</span>
          </div>
        ))}
      </div>

      <div className="mt-4 rounded-xl border border-zinc-200 bg-white p-4 sm:ml-16">
        <p className="mb-1 text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Project</p>
        <p className="text-sm font-semibold leading-6 text-zinc-800">{phase.project}</p>
      </div>
    </article>
  );
}

function parseRoadmap(text: string, path: string, level: string): GeneratedRoadmap {
  const cleaned = text
    .replace(/```(?:json)?/gi, '')
    .trim();
  const jsonStart = cleaned.indexOf('{');
  const jsonEnd = cleaned.lastIndexOf('}');

  if (jsonStart === -1 || jsonEnd === -1) {
    return parseMarkdownTableRoadmap(cleaned, path, level);
  }

  try {
    const parsed = JSON.parse(cleaned.slice(jsonStart, jsonEnd + 1)) as Partial<GeneratedRoadmap>;
    if (!Array.isArray(parsed.phases) || parsed.phases.length === 0) {
      return parseMarkdownTableRoadmap(cleaned, path, level);
    }

    return {
      title: parsed.title || `${capitalize(level)} ${path} Roadmap`,
      estimatedTime: parsed.estimatedTime || 'Estimated time: 4-8 months',
      summary: parsed.summary || 'A practical roadmap generated for your selected goal.',
      phases: parsed.phases.slice(0, 5).map((phase, index) => ({
        phase: Number(phase.phase) || index + 1,
        title: phase.title || `Phase ${index + 1}`,
        goal: phase.goal || 'Build confidence with practical learning and small projects.',
        items: Array.isArray(phase.items) ? phase.items.slice(0, 4).map(String) : [],
        project: phase.project || 'Build a small portfolio-ready project using this phase.',
      })),
    };
  } catch {
    return parseMarkdownTableRoadmap(cleaned, path, level);
  }
}

function parseMarkdownTableRoadmap(text: string, path: string, level: string): GeneratedRoadmap {
  const rows = text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('|') && !line.includes('---'));

  const phases = rows.slice(1, 6).map((row, index) => {
    const columns = row
      .split('|')
      .map((cell) => cell.trim().replace(/\*\*/g, ''))
      .filter(Boolean);
    const title = columns[1] || `Phase ${index + 1}`;
    const itemCell = columns[2] || '';
    const items = itemCell
      .replace(/<br\s*\/?>/gi, '\n')
      .split(/\n|\d+\.\s+/)
      .map((item) => item.trim())
      .filter(Boolean)
      .slice(0, 4);

    return {
      phase: Number(columns[0]) || index + 1,
      title,
      goal: `Focus on ${title.toLowerCase()} with practical, project-based learning.`,
      items: items.length ? items : ['Study the core concepts', 'Practice with examples', 'Build a mini feature', 'Review and refine your work'],
      project: `Create a small ${title.toLowerCase()} project for your portfolio.`,
    };
  });

  if (phases.length === 0) {
    return parseLooseTextRoadmap(text, path, level);
  }

  return {
    title: `${capitalize(level)} ${path} Roadmap`,
    estimatedTime: 'Estimated time: 4-8 months',
    summary: 'A structured roadmap generated from the AI response.',
    phases,
  };
}

function parseLooseTextRoadmap(text: string, path: string, level: string): GeneratedRoadmap {
  const normalized = text
    .replace(/\r/g, '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/\*\*/g, '')
    .trim();

  const chunks = normalized
    .split(/(?=^#{0,4}\s*(?:Phase\s*)?\d+[\).:\-\s]|^#{1,4}\s*Phase\s*\d+)/gim)
    .map((chunk) => chunk.trim())
    .filter(Boolean);

  const phaseChunks = chunks.filter((chunk) => /(?:phase\s*)?\d+/i.test(chunk)).slice(0, 5);

  const phases = phaseChunks.map((chunk, index) => {
    const lines = chunk
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean);
    const heading = lines[0]
      ?.replace(/^#{1,4}\s*/, '')
      .replace(/^phase\s*/i, '')
      .replace(/^\d+[\).:\-\s]*/, '')
      .trim();
    const title = heading || `Phase ${index + 1}`;
    const itemLines = lines
      .slice(1)
      .flatMap((line) => line.split(/(?:^|\s)\d+\.\s+/))
      .map((line) => line.replace(/^[-*•]\s*/, '').trim())
      .filter((line) => line.length > 8 && !/^goal:|^project:/i.test(line))
      .slice(0, 4);
    const projectLine = lines.find((line) => /^project:/i.test(line))?.replace(/^project:\s*/i, '');
    const goalLine = lines.find((line) => /^goal:/i.test(line))?.replace(/^goal:\s*/i, '');

    return {
      phase: index + 1,
      title,
      goal: goalLine || `Focus on ${title.toLowerCase()} with hands-on practice.`,
      items: itemLines.length >= 2 ? itemLines : buildDefaultItems(title),
      project: projectLine || `Build a practical ${title.toLowerCase()} mini project.`,
    };
  });

  const finalPhases = phases.length ? phases : buildDefaultRoadmap(path);

  return {
    title: `${capitalize(level)} ${path} Roadmap`,
    estimatedTime: 'Estimated time: 4-8 months',
    summary: phases.length
      ? 'A structured roadmap generated from the AI response.'
      : 'The AI response was loose, so this page created a clean roadmap layout from your selected goal.',
    phases: finalPhases,
  };
}

function buildDefaultItems(title: string) {
  return [
    `Learn the key concepts of ${title.toLowerCase()}`,
    `Practice the most common ${title.toLowerCase()} patterns`,
    `Build one focused feature using this phase`,
    `Review, refactor, and document what you learned`,
  ];
}

function buildDefaultRoadmap(path: string): RoadmapPhase[] {
  const titles = ['Foundations', 'Core Skills', 'Frameworks and Tools', 'Testing and APIs', 'Deployment and Portfolio'];
  return titles.map((title, index) => ({
    phase: index + 1,
    title,
    goal: `Develop ${title.toLowerCase()} for the ${path} path.`,
    items: buildDefaultItems(title),
    project: `Create a ${title.toLowerCase()} project for your ${path} portfolio.`,
  }));
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
